kind: pipeline
name: deploy_home_stack

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker ps -a
- name: deploy
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker stack deploy -c ./Docker/Stacks/Download/docker-compose-download.yml download
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock